### ISSUE TITLE
Train netwrok with different values for m and n

### ISSUE THREAD

**Issue by nataliaasaa** [KalmanNet/KalmanNet_TSP#12]
With kalman filter (from filterpy for example) it's possible to have different dimension for the state and the observation, so for example you can have a problem were you have your state with dimention 4 but observation with dimension 7. Is it possible to do the same with KalmanNet?

**Comment by XiaoyongNI** [comment]
Hi, Thanks for your question!

Similar with kalman filter, KalmanNet can also handle the case where m and n takes different values.

Specifically, you could call the **_SystemModel_** function (in Linear_sysmdl.py or Extended_sysmdl.py), and input it with the F and H matrices (or non-linear f(.) and h(.), m and n) having dimensions as you want. After that, you just provide KalmanNet with this **_SystemModel_** (similar as I did in main_linear.py or main_lorenz.py), and KalmanNet would adjust itself accordingly.

Best, Xiaoyong
