### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by jer1ry** [KalmanNet/KalmanNet_TSP#13]
hello
problem 1:When I use the project code you designed, there is an error in importing the parameters, model, filterpy.kalman, and pyparticleest packages, but these files are in the project folder.
problem 2: Can you elaborate more on how to use the entire project

**Comment by XiaoyongNI** [comment]
Hi, thanks for your question!

problem1: For filterpy and pyparticleest, these 2 packages are not in this repo, you need to install them using e.g. **_pip install filterpy_** and **_pip install pyParticleEst_**.
For parameters.py and model.py, first check whether you have imported sys module correctly. If the problem still exists, try to substitute 
**_import sys
sys.path.insert(1, path_model)
from parameters import ...
from model import ..._**
with
**_from Simulations.Lorenz_Atractor.parameters import ...
from Simulations.Lorenz_Atractor.model import..._**

problem2: 
Briefly, KalmanNet could solve various filtering problems just as the celebrated Kalman Filter did, and its advantage in performance mainly comes in non-linear, unknown noise statistics (q and r) and partially known dynamics (f and h) cases.

You could modify main_linear.py and main_lorenz.py with your specific system model (f/F, h/H, m, n, q, r, T), generate dataset, train KalmanNet and deploy with the trained model.

For more details, please refer to README.md where I wrote explanations for each py file in both 2 branches.

Best, Xiaoyong

**Comment by jer1ry** [comment]
Sorry, I just saw your reply now, thank you very much, I will read your reply carefully！
Best, Liuxuan




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KalmanNet/KalmanNet_TSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月12日(星期一) 晚上8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KalmanNet/KalmanNet_TSP] code error (Issue #13)





 
Hi, thanks for your question!
 
problem1: For filterpy and pyparticleest, these 2 packages are not in this repo, you need to install them using e.g. pip install filterpy and pip install pyParticleEst.
 For parameters.py and model.py, first check whether you have imported sys module correctly. If the problem still exists, try to substitute
 import sys
 sys.path.insert(1, path_model)
 from parameters import ...
 from model import ...
 with
 from Simulations.Lorenz_Atractor.parameters import ...
 from Simulations.Lorenz_Atractor.model import...
 
problem2:
 Briefly, KalmanNet could solve various filtering problems just as the celebrated Kalman Filter did, and its advantage in performance mainly comes in non-linear, unknown noise statistics (q and r) and partially known dynamics (f and h) cases.
 
You could modify main_linear.py and main_lorenz.py with your specific system model (f/F, h/H, m, n, q, r, T), generate dataset, train KalmanNet and deploy with the trained model.
 
For more details, please refer to README.md where I wrote explanations for each py file in both 2 branches.
 
Best, Xiaoyong
