### ISSUE TITLE
Question: Can you explain why you get the training data randomly?

### ISSUE THREAD

**Issue by lcamhoa** [KalmanNet/KalmanNet_TSP#15]
Can you explain why you get the training data randomly?https://github.com/KalmanNet/KalmanNet_TSP/blob/main/Pipeline_EKF.py#L105

**Comment by XiaoyongNI** [comment]
This is the same as shuffling the dataset during training. The goal is to minimize the risk to create batches that are not representative of the dataset, leading to deviated gradient computation.
