### ISSUE TITLE
Help needed: strange results with Google Colab

### ISSUE THREAD

**Issue by hadlaczkyb** [KalmanNet/KalmanNet_TSP#3]
Hi!
In our research project we started to work with the KalmanNet. As a first step, we only tried the simple linear case using the 2x2 linear system (2x2_020_T100.pt). For this, we imported the following files to Google Colab and ran a learning and testing sequence:

- KalmanNet_nn.py

- Linear_KF.py 

- Linear_sysmdl.py 

- Extended_data.py

- Pipeline_KF.py 

- KalmanFilter_test.py

- main_linear.py 

- Plot.py

We found the following behaviour: using the same code as in the GitHub repository and the same files, in some cases the results look rather promising:

 
![kép](https://user-images.githubusercontent.com/72016483/143040037-35139b1c-7625-4287-a7ac-bd5737f7b936.png)

 
![kép](https://user-images.githubusercontent.com/72016483/143040843-d5cb860f-5893-442c-a2c9-d1d2d87867c1.png)

But in other cases – without any modifications applied – the results look like this:
 
![kép](https://user-images.githubusercontent.com/72016483/143040119-a9f5d46c-c85e-4214-9b65-68fadac6021d.png)

 
![kép](https://user-images.githubusercontent.com/72016483/143040138-b94a9849-979e-463a-ad4a-4a6eb2c336b7.png)

The strange thing is that the system, the data, the hyperpaparmeters and the length of the learning sequence are the same, however the results seem to converge to different values: sometimes to -7db/-8dB and sometimes to 0dB.
Unfortunately we haven’t come up with an explanation so far, so we would be much obliged if you could give us a helping hand what might went wrong in our side.
Thanks in advance!

**Comment by XiaoyongNI** [comment]
This is possibly because that KalmanNet has been trained to converge to some local optimal. One solution to this is try to use larger weight decay and larger numbers of training epoches.
