### ISSUE TITLE
Some Small Errors i detected  

### ISSUE THREAD

**Issue by UlysseasKarachalios** [KalmanNet/KalmanNet_TSP#32]
Greetings dear authors ,

Thank you very much for uploading your really interesting work !
While i was working with the code i noticed some small errors and thought i thought about proposing some corrections . 

1) In file Pipeline_EKF.py  :

Line 10

from Plot import Plot_KF

should be changed to

from Plot import Plot_RTS    *or*  from Plot import Plot_extended 

so that line 348 is functional after changing line 343 to

self.Plot =Plot_RTS(self.folderName, self.modelName) *or* self.Plot =Plot_extended(self.folderName, self.modelName) .

2) Same problem with file main_linear_CA.py :

Line 17

from Plot import Plot_KF as Plot

should be changed to

from Plot import Plot_RTS as Plot   *or*   from Plot import Plot_extended

so that lines 182 -184 are functional .

3) In file KalmanNet_nn.py :

Lines 220 and 228

in_FC5 = fw_evol_diff

in_FC6 = fw_update_diff

should be changed as :

in_FC5 = fw_update_diff

in_FC6 = fw_evol_diff

so to follow the illustration in figure 4 of the KalmanNet paper (https://arxiv.org/pdf/2107.10043.pdf) at page 6 . The forward update difference is used on the estimation of covariance **Q** instead the of the forward innovation difference feature . So , the estimation of covariance **Σ** should be changed accordingly . 

Best regards ,
Odysseas Karachalios

**Comment by XiaoyongNI** [comment]
Thanks Odysseas, these errors have been corrected.
