### ISSUE TITLE
Run on Jupyter notebook

### ISSUE THREAD

**Issue by kmh6935** [KalmanNet/KalmanNet_TSP#33]
Hello, 

I am trying to run "main_linear_canonical.py" on Jupyter Notebook.
So I converted "main_linear_canonical.py" to "main_linear_canonical.ipynb", and run it on Jupyter notebook.
However, I got this error message below:

usage: KalmanNet [-h] [--N_E trainset-size] [--N_CV cvset-size] [--N_T testset-size] [--T length]
                 [--T_test test-length] [--randomLength rl] [--T_max maximum-length] [--T_min minimum-length]
                 [--randomInit_train ri_train] [--randomInit_cv ri_cv] [--randomInit_test ri_test]
                 [--variance variance] [--distribution distribution] [--use_cuda CUDA] [--n_steps N_steps]
                 [--n_batch N_B] [--lr LR] [--wd WD] [--CompositionLoss loss] [--alpha alpha]
                 [--in_mult_KNet in_mult_KNet] [--out_mult_KNet out_mult_KNet]
KalmanNet: error: unrecognized arguments: -f C:\Users\ko.444\AppData\Roaming\jupyter\runtime\kernel-f784040b-73c0-494f-936f-db7a81c2959c.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
C:\Users\ko.444\AppData\Local\anaconda3\envs\kalmannet\Lib\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

I believe the error results from line "args = config.general_settings()"

What happened here and I was wondering how I can resolve this issue.

Thank you in advance.

**Comment by KhlYanis** [comment]
Hello, 

Just had the same issue. To solve it, you have to modify the line 62 of config.py and put args = parser.parse_args("") instead of args = parser.parse_args() 

Hope this works for you
