### ISSUE TITLE
errors on running stock code (error on using GPU and CPU)

### ISSUE THREAD

**Issue by gedaimaster** [KalmanNet/KalmanNet_TSP#6]
Hi, your research is very interesting. I am trying to reproduce your results but I am having errors specifically when running the UKF evaluation which also occurs when I'm running PF test. My first error I encountered is this.

![messageImage_1649141501214](https://user-images.githubusercontent.com/55107784/161722693-b4d45a9b-930d-4f51-b3f8-ccbf85e985f8.jpg)

When I tried to edit the files on the UKF_test.py, adding .cpu, I now get this error.

![messageImage_1649141659815](https://user-images.githubusercontent.com/55107784/161722786-0dc38a70-99dd-46aa-91bb-e8c979c91e62.jpg)

I then tried to change the codes to only run torch on CPU but it is still not working.

I am using python 3.10, CUDA 11.3 for pytorch and no specific version for
matplotlib, seaborn, filterpy, and pyparticleest which I installed when needed during import.
I hope I can get some help. Thank you!

**Comment by XiaoyongNI** [comment]
Hi,

This problem possibly comes from that the loaded dataset, i.e. "test_input" and "test_target" are on GPU, try to use torch.load(map_location=torch.device("cpu")) to load your data.

**Comment by binjiaqm** [comment]
Same issue here. Seems many issues in the code.
