### ISSUE TITLE
how to plot???

### ISSUE THREAD

**Issue by Dowe-dong** [KalmanNet/KalmanNet_TSP#8]
please ask:how to Visualize?

**Comment by goodChiken** [comment]
how to run the plot.py???

**Comment by XiaoyongNI** [comment]
In the main files, you can instantiate using e.g. Plot = Plot(PlotfolderName, PlotResultName).

The class "Plot_RTS" is for linear case while the class "Plot_extended" is for non-linear. Specifically, inside the classes, I defined the NNPlot_epochs() function to plot the training process, the NNPlot_Hist() to plot histograms. For non-linear case, you could also use plotTrajectories() to plot the Lorenz Attractor data in our simulations.

**Comment by lhw20** [comment]
> In the main files, you can instantiate using e.g. Plot = Plot(PlotfolderName, PlotResultName).
> 
> The class "Plot_RTS" is for linear case while the class "Plot_extended" is for non-linear. Specifically, inside the classes, I defined the NNPlot_epochs() function to plot the training process, the NNPlot_Hist() to plot histograms. For non-linear case, you could also use plotTrajectories() to plot the Lorenz Attractor data in our simulations.

Does class "Plot_RTS" really work for linear case in this paper about KalmanNet rather than another one about RTSNET?

**Comment by XiaoyongNI** [comment]
> > In the main files, you can instantiate using e.g. Plot = Plot(PlotfolderName, PlotResultName).
> > The class "Plot_RTS" is for linear case while the class "Plot_extended" is for non-linear. Specifically, inside the classes, I defined the NNPlot_epochs() function to plot the training process, the NNPlot_Hist() to plot histograms. For non-linear case, you could also use plotTrajectories() to plot the Lorenz Attractor data in our simulations.
> 
> Does class "Plot_RTS" really work for linear case in this paper about KalmanNet rather than another one about RTSNET?

It should work for both, let me know if you find any bugs.

Thanks,
Xiaoyong
