### ISSUE TITLE
Input feature size meanning

### ISSUE THREAD

**Issue by lcamhoa** [KalmanNet/KalmanNet_TSP#9]
Hi,

Can you please give the detail of  model's  input + output size? When I debug it shows that 
```
train_input.shape = size(1000, 2, 100)
train_target.shape = size(1000, 2, 100)
cv_input.shape = size(1000, 2, 100)
cv_target.shape = size(1000, 2, 100)
test_input.shape = size(1000, 2, 100)
test_target.shape = size(1000, 2, 100)
```

**Comment by XiaoyongNI** [comment]
Hi,

The meaning of feature size is (Number of trajectories, state/observation dimension, trajectory length).
So in your case, 
Number of trajectories = 1000
state/observation dimension = 2
trajectory length = 100

Best,
Xiaoyong
